## 성인 가해자 관련 자료 분석

In [1]:
# 모듈 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 작성기관 : 방송통신위원회 인터넷이용과정책과 인터넷이용과정책과 (☎ 02-2110-1522)

# 조사기관 : 사이버폭력 경험 및 인식 현황 등을 파악하여 사이버폭력 예방과 대응 정책 수립의 기초자료로 활용하기 위함

# 통계(활용)분야 · 실태 : 범죄·안전


# <조사 대상 범위>

# 청소년 : 초등학교 4학년 이상 중·고등학생 학령별 각 3,000명
# 
성인 : 전국 17개 시·도의 7,500가구 내 만 20세 이상 69세 이하 가구원 중 최근 1개월 이내 1회 이상 인터넷 또는 스마트폰을 이 자용한
# 

<조사단위 및 조사대상 규모# >
-개# 
-
(학생) 조사 기준일(2021. 9. 1) 현재 전국의 초등학교 4학년부터 고등학교 3학년까지 재학중인 학생 9,0# -

(성인) 조사 기준일(2021. 9. 1) 현재 대한민국에 상주하는 만20세 이상 69세 이하 국민 중 최근 1개월 이내 1회 이상 인터넷 또는 스마트폰을 이용한(외국인 제외) 일반 성인 7,0명 자

In [27]:
# ================================================================================
# 함수 이름 : clean
# 함수 기능 : 행과 열 인덱스를 맞춤
# 변     수 : 파일을 지정해야하여 변수로 설정해야함
# ----------------------------------------------------------
def clean(file):
    # 1열은 필요없으므로 건너뛴 상태로 csv파일 부름
    F = pd.read_csv(file, skiprows = 1)       

    # 형변환
    F['특성별(1)'] = F['특성별(1)'].astype('category')
    F['특성별(2)'] = F['특성별(2)'].astype('category')

    # 멀티인덱스 설정
    F.set_index(['특성별(1)','특성별(2)'], inplace = True)

    # 정보 확인
    F.info()                

    return F

In [3]:
file1 = '../성인_가해경험/사이버폭력_가해_경험_20240119170321.csv'

# 결과값으로 info() 출력
cyberDF1 = clean(file1)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   가해 경험률    52 non-null     float64
 1   사이버 언어폭력  52 non-null     float64
 2   사이버 명예훼손  52 non-null     float64
 3   사이버 스토킹   52 non-null     float64
 4   사이버 성폭력   52 non-null     float64
 5   신상정보 유출   52 non-null     float64
 6   사이버 따돌림   52 non-null     float64
 7   사이버 갈취    52 non-null     float64
 8   사이버 강요    52 non-null     float64
dtypes: float64(9)
memory usage: 7.1 KB

In [4]:
def withdraw(cyberDF):
    #cyberDF파일에서 연령별 자료 추출
    cyberDF_age=cyberDF.xs('연령별', level = 0)

    #cyberDF파일에서 학력별 자료 추출
    cyberDF_edu=cyberDF.xs('학력별', level = 0)

    #cyberDF파일에서 소득별 자료 추출
    cyberDF_income=cyberDF.xs('월평균 가구소득별', level = 0)

    return cyberDF_age.T, cyberDF_edu.T, cyberDF_income.T

In [26]:
# 사이버폭력_가해_경험_연령별, 학력별, 소득별 자료 추출
cyberDF1_age, cyberDF1_edu, cyberDF1_income = withdraw(cyberDF1)
cyberDF1_age

특성별(2)    19~29세  30~39세  40~49세  50~59세  60~69세
가해 경험률       7.4     4.2     3.9     2.0     1.6
사이버 언어폭력     6.2     3.4     3.2     1.5     0.8
사이버 명예훼손     2.2     1.4     1.1     0.6     0.6
사이버 스토킹      1.8     1.3     1.4     0.5     0.5
사이버 성폭력      1.0     1.6     0.9     0.7     0.7
신상정보 유출      1.3     0.7     0.5     0.6     0.5
사이버 따돌림      1.4     1.2     0.7     0.7     0.5
사이버 갈취       1.0     1.2     0.6     0.5     0.4
사이버 강요       1.1     1.0     0.7     0.7     0.4

In [6]:
cyberDF1_edu

특성별(2)    초졸이하   중졸   고졸  대졸이상
가해 경험률     0.0  2.0  3.0   4.6
사이버 언어폭력   0.0  1.7  2.3   3.7
사이버 명예훼손   0.0  0.3  1.0   1.4
사이버 스토킹    0.0  0.3  0.8   1.4
사이버 성폭력    0.0  0.6  0.8   1.1
신상정보 유출    0.0  0.0  0.7   0.8
사이버 따돌림    0.0  0.6  0.8   1.0
사이버 갈취     0.0  0.3  0.6   0.8
사이버 강요     0.0  0.0  0.6   1.0

In [7]:
cyberDF1_income

특성별(2),100만원 미만,100~200만원 미만,200~300만원 미만,300~400만원 미만,400~500만원 미만,500~600만원 미만,600~700만원 미만,700만원 이상
가해 경험률,1.6,2.5,2.9,3.4,5.6,5.0,2.5,1.8
사이버 언어폭력,1.6,2.5,2.2,2.7,4.1,4.1,2.3,1.2
사이버 명예훼손,0.8,0.0,0.8,0.9,2.2,1.4,0.5,0.8
사이버 스토킹,0.8,0.8,0.4,0.8,2.0,1.8,0.6,0.2
사이버 성폭력,0.0,0.3,0.8,0.8,1.9,1.3,0.0,0.4
신상정보 유출,0.0,0.3,0.2,0.5,1.3,1.6,0.0,0.0
사이버 따돌림,0.0,0.0,0.3,0.6,2.0,1.8,0.0,0.0
사이버 갈취,0.0,0.0,0.2,0.4,1.9,1.3,0.2,0.0
사이버 강요,0.0,0.0,0.1,0.5,1.7,1.6,0.2,0.0

In [8]:
# 사이버폭력_가해_경험_경로_연령별, 학력별, 소득별 자료 추출
file2 = '../성인_가해경험/사이버폭력_가해_경험_경로_20240121162324.csv'
cyberDF2 = clean(file2)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50 entries, ('전체', '소계') to ('사이버폭력예방교육별', '경험 없음')
Data columns (total 7 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   문자 및 인스턴트 메시지 (카카오톡 라인 페이스북 메신저 텔레그램 등)  50 non-null     float64
 1   SNS (페이스북 인스타그램 블로그 등)                   50 non-null     float64
 2   온라인 게임                                   50 non-null     float64
 3   커뮤니티·동호회 (네이버·다음카페 블라인드 에스크 등)           50 non-null     float64
 4   개인 방송 서비스 (유튜브 아프리카TV 트위치 틱톡 등)          50 non-null     float64
 5   메타버스 (제페토 이프렌드 등)                        50 non-null     float64
 6   기타                                       50 non-null     float64
dtypes: float64(7)
memory usage: 6.2 KB

In [9]:
# 사이버폭력_가해_경로_연령별, 학력별, 소득별 자료 추출
cyberDF2_age, cyberDF2_edu, cyberDF2_income = withdraw(cyberDF2)
cyberDF2_age

특성별(2),19~29세,30~39세,40~49세,50~59세,60~69세
문자 및 인스턴트 메시지 (카카오톡 라인 페이스북 메신저 텔레그램 등),41.5,50.7,40.6,54.9,68.3
SNS (페이스북 인스타그램 블로그 등),23.8,11.3,10.2,5.7,11.1
온라인 게임,41.4,40.2,31.4,9.0,3.6
커뮤니티·동호회 (네이버·다음카페 블라인드 에스크 등),7.3,12.0,21.3,36.2,35.3
개인 방송 서비스 (유튜브 아프리카TV 트위치 틱톡 등),7.5,3.6,4.5,0.0,0.0
메타버스 (제페토 이프렌드 등),2.1,0.0,0.0,0.0,0.0
기타,0.0,1.4,3.6,3.0,0.0

In [10]:
# 사이버폭력__연령별, 학력별, 소득별 자료 추출
file3 = '../성인_가해경험/사이버폭력_가해자_유형_20240119170714.csv'
cyberDF3 = clean(file3)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   전혀 모르는 사람      52 non-null     float64
 1   친한 친구          52 non-null     float64
 2   선후배            52 non-null     float64
 3   얼굴만 아는 사이      52 non-null     float64
 4   온라인에서 알게 된 사람  52 non-null     float64
 5   동료             52 non-null     float64
dtypes: float64(6)
memory usage: 5.9 KB

In [11]:
# 사이버폭력_가해자_유형_연령별, 학력별, 소득별 자료 추출
cyberDF3_age, cyberDF3_edu, cyberDF3_income = withdraw(cyberDF3)
cyberDF3_age

특성별(2)         19~29세  30~39세  40~49세  50~59세  60~69세
전혀 모르는 사람        57.5    65.6    68.0    67.3    61.1
친한 친구            12.0     9.1     3.8     6.1    10.0
선후배               5.2     3.8     7.5     3.3     1.9
얼굴만 아는 사이        11.7     6.6    12.5     8.0    13.2
온라인에서 알게 된 사람    11.0    10.2     2.9     7.3     7.5
동료                2.7     4.8     5.2     8.0     6.4

In [12]:
file4 = '../성인_가해경험/사이버폭력_가해_대상_복수_응답__20240122000016.csv'
cyberDF4 = clean(file4)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   친한 친구          50 non-null     float64
 1   선후배            50 non-null     float64
 2   전혀 모르는 사람      50 non-null     float64
 3   유명인            50 non-null     float64
 4   동료             50 non-null     float64
 5   얼굴만 아는 사이      50 non-null     float64
 6   온라인에서 알게 된 사람  50 non-null     float64
dtypes: float64(7)
memory usage: 6.2 KB

In [13]:
# 사이버폭력_가해 대상_연령별, 학력별, 소득별 자료 추출
cyberDF4_age, cyberDF4_edu, cyberDF4_income = withdraw(cyberDF4)
cyberDF4_age

특성별(2)         19~29세  30~39세  40~49세  50~59세  60~69세
친한 친구            16.8    13.9     6.1    12.5    13.4
선후배               3.9     5.0     6.6     0.0     3.9
전혀 모르는 사람        51.9    53.5    54.2    39.1    59.6
유명인              20.6     9.7    13.3    20.7    14.5
동료                1.2     4.7     3.1     3.0     0.0
얼굴만 아는 사이         2.0     8.0    18.2     6.2     0.0
온라인에서 알게 된 사람     7.6    10.3     6.7    21.6    13.4

In [14]:
# 사이버폭력_심리 상태_연령별, 학력별, 소득별 자료 추출 (1) 정당하다고 생각하는 의견
file5 = '../성인_가해경험/사이버폭력_가해_경험_후_심리상태__정당한_행동이라_생각했음_20240122001016.csv'
cyberDF5 = clean(file5)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50 entries, ('전체', '소계') to ('사이버폭력예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  50 non-null     float64
 1   그렇지 않다     50 non-null     float64
 2   그렇다        50 non-null     float64
 3   매우 그렇다     50 non-null     float64
dtypes: float64(4)
memory usage: 5.0 KB

In [15]:
# 사이버폭력_심리 상태_연령별, 학력별, 소득별 자료 추출 (1) 정당하다고 생각하는 의견
cyberDF5_age, cyberDF5_edu, cyberDF5_income = withdraw(cyberDF5)
cyberDF5_age

특성별(2)     19~29세  30~39세  40~49세  50~59세  60~69세
전혀 그렇지 않다    19.8    16.5    18.0     6.0     0.0
그렇지 않다       44.9    34.4    27.2    43.5    49.7
그렇다          28.1    44.2    49.5    50.5    50.3
매우 그렇다        7.2     4.9     5.3     0.0     0.0

In [16]:
# 사이버폭력_심리 상태_연령별, 학력별, 소득별 자료 추출 (2) 아무느낌도 없음
file6 = '../성인_가해경험/사이버폭력_가해_경험_후_심리상태__아무런_느낌이_없었음_20240122001054.csv'
cyberDF6 = clean(file6)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50 entries, ('전체', '소계') to ('사이버폭력예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  50 non-null     float64
 1   그렇지 않다     50 non-null     float64
 2   그렇다        50 non-null     float64
 3   매우 그렇다     50 non-null     float64
dtypes: float64(4)
memory usage: 5.0 KB

In [17]:
cyberDF6_age, cyberDF6_edu, cyberDF6_income = withdraw(cyberDF6)
cyberDF6_age

특성별(2)     19~29세  30~39세  40~49세  50~59세  60~69세
전혀 그렇지 않다    23.9    16.7    24.5    11.4     0.0
그렇지 않다       37.8    48.6    37.9    53.4    26.9
그렇다          35.1    31.8    29.8    35.2    69.4
매우 그렇다        3.2     2.9     7.8     0.0     3.8

In [18]:
# 사이버폭력_심리 상태_연령별, 학력별, 소득별 자료 추출 (3)문제가 생길 것 같아 걱정되었음.
file7 = '../성인_가해경험/사이버폭력_가해_경험_후_심리상태__문제가_생길_것_같아_걱정되었음_20240122001033.csv'
cyberDF7 = clean(file7)
cyberDF7_age, cyberDF7_edu, cyberDF7_income = withdraw(cyberDF7)
cyberDF7_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50 entries, ('전체', '소계') to ('사이버폭력예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  50 non-null     float64
 1   그렇지 않다     50 non-null     float64
 2   그렇다        50 non-null     float64
 3   매우 그렇다     50 non-null     float64
dtypes: float64(4)
memory usage: 5.0 KB

특성별(2)     19~29세  30~39세  40~49세  50~59세  60~69세
전혀 그렇지 않다    18.5    18.3    24.9     9.3    11.0
그렇지 않다       46.0    51.1    38.5    57.2    38.7
그렇다          33.5    27.7    35.1    30.3    42.8
매우 그렇다        2.0     2.9     1.5     3.2     7.5

In [19]:
# 사이버폭력_심리 상태_연령별, 학력별, 소득별 자료 추출 (4)흥미롭고 재미있었음.
file8 = '../성인_가해경험/사이버폭력_가해_경험_후_심리상태__흥미롭고_재미있었음_20240122001044.csv'
cyberDF8 = clean(file8)
cyberDF8_age, cyberDF8_edu, cyberDF8_income = withdraw(cyberDF8)
cyberDF8_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50 entries, ('전체', '소계') to ('사이버폭력예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  50 non-null     float64
 1   그렇지 않다     50 non-null     float64
 2   그렇다        50 non-null     float64
 3   매우 그렇다     50 non-null     float64
dtypes: float64(4)
memory usage: 5.0 KB

특성별(2)     19~29세  30~39세  40~49세  50~59세  60~69세
전혀 그렇지 않다    27.6    22.4    28.4    15.5     7.4
그렇지 않다       40.6    54.4    45.5    56.3    51.0
그렇다          29.6    23.2    22.9    22.3    41.7
매우 그렇다        2.2     0.0     3.2     5.9     0.0

In [20]:
# 사이버폭력_심리 상태_연령별, 학력별, 소득별 자료 추출 (5) 상대방에게 미안하고 후회스러움.
file9 = '../성인_가해경험/사이버폭력_가해_경험_후_심리상태__상대방에게_미안하고_후회스러웠음_20240122001024.csv'
cyberDF9 = clean(file9)
cyberDF9_age, cyberDF9_edu, cyberDF9_income = withdraw(cyberDF9)
cyberDF9_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50 entries, ('전체', '소계') to ('사이버폭력예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  50 non-null     float64
 1   그렇지 않다     50 non-null     float64
 2   그렇다        50 non-null     float64
 3   매우 그렇다     50 non-null     float64
dtypes: float64(4)
memory usage: 5.0 KB

특성별(2)     19~29세  30~39세  40~49세  50~59세  60~69세
전혀 그렇지 않다    16.4    21.5    25.3     8.7     7.3
그렇지 않다       38.2    42.4    35.2    63.5    43.7
그렇다          42.3    31.5    33.2    27.8    41.5
매우 그렇다        3.1     4.7     6.4     0.0     7.5