## 학생 가해자 유형

In [1]:
# 모듈 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# ================================================================================
# 함수 이름 : clean
# 함수 기능 : 행과 열 인덱스를 맞춤
# 변     수 : 파일을 지정해야하여 변수로 설정해야함
# ----------------------------------------------------------
def clean(file):
    # 1열은 필요없으므로 건너뛴 상태로 csv파일 부름
    F = pd.read_csv(file, skiprows = 1)       

    # 형변환
    F['특성별(1)'] = F['특성별(1)'].astype('category')
    F['특성별(2)'] = F['특성별(2)'].astype('category')

    # 멀티인덱스 설정
    F.set_index(['특성별(1)','특성별(2)'], inplace = True)

    # 정보 확인
    F.info()                

    return F

In [3]:
file1 = '../학생_가해경험/사이버폭력_가해_경험_20240119191526.csv'

# 결과값으로 info() 출력
cyberDF1 = clean(file1)
cyberDF1

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   가해 경험률    30 non-null     float64
 1   사이버 언어폭력  30 non-null     float64
 2   사이버 명예훼손  30 non-null     float64
 3   사이버 스토킹   30 non-null     float64
 4   사이버 성폭력   30 non-null     float64
 5   신상정보 유출   30 non-null     float64
 6   사이버 따돌림   30 non-null     float64
 7   사이버 갈취    30 non-null     float64
 8   사이버 강요    30 non-null     float64
dtypes: float64(9)
memory usage: 4.0 KB

                      가해 경험률  사이버 언어폭력  사이버 명예훼손  사이버 스토킹  사이버 성폭력  신상정보 유출  \
특성별(1)      특성별(2)
전체          소계          20.6      19.2       5.3      2.0      1.8      2.5
성별          남학생         26.6      24.9       7.0      3.0      2.6      3.4
            여학생         14.1      13.1       3.6      1.0      0.9      1.5
학령별         초등학교        22.1      19.9       5.7      1.9      1.5      1.8
            중학교         24.8      23.6       6.9      2.8      2.3      3.8
            고등학교        14.5      13.9       3.3      1.5      1.5      1.8
학교특성별       남학교         24.6      23.3       7.2      2.7      2.6      3.7
            여학교         11.4      10.5       2.8      0.9      0.7      0.9
            남녀공학        20.2      19.3       5.1      2.2      1.9      2.9
거주지역별       대도시         18.4      17.3       4.9      2.0      1.4      2.1
            중소도시        22.1      20.5       5.9      2.2      2.2      2.8
            읍면지역        21.1      20.0       4.3      1.6      1.2      2.4
권역별         수도권         20.5      19.3       4.9      2.0      1.7      2.4
            충청권         21.7      20.4       6.2      3.3      2.9      3.3
            호남권         21.0      19.8       5.0      2.1      2.1      2.7
            동북권         19.5      17.7       5.7      1.7      1.7      2.1
            동남권         20.5      18.8       5.9      1.6      1.1      2.2
인터넷 이용 시간별  1시간 미만       9.7       7.4       3.0      2.3      1.8      1.4
            1~2시간 미만    15.1      13.7       3.6      1.6      1.2      2.1
            2~3시간 미만    18.2      16.6       4.2      1.7      1.8      1.7
            3~5시간 미만    24.1      22.9       7.0      2.2      2.0      2.9
            5시간 이상      25.9      24.8       6.4      2.5      2.0      3.3
가정형편별       상위          19.7      18.0       6.9      3.6      3.3      3.7
            중위          20.7      19.4       5.0      1.7      1.4      2.2
            하위          19.8      17.2       7.8      5.5      6.0      6.3
학업성적별       상위권         19.7      18.1       5.9      2.6      2.2      3.1
            중위권         20.7      19.5       5.1      1.7      1.5      2.1
            하위권         21.4      19.2       6.1      3.7      3.5      3.9
사이버폭력 예방교육별 경험 있음       20.8      19.6       5.2      1.7      1.5      2.2
            경험 없음       18.8      16.0       6.5      4.4      4.1      4.7

                      사이버 따돌림  사이버 갈취  사이버 강요
특성별(1)      특성별(2)
전체          소계            2.3     1.6     1.6
성별          남학생           3.2     2.5     2.2
            여학생           1.4     0.6     0.9
학령별         초등학교          2.7     1.1     1.6
            중학교           2.6     2.3     1.9
            고등학교          1.7     1.4     1.2
학교특성별       남학교           2.6     2.6     2.0
            여학교           0.7     0.4     0.6
            남녀공학          2.3     1.9     1.6
거주지역별       대도시           1.8     1.4     1.2
            중소도시          2.8     1.8     1.9
            읍면지역          2.2     1.3     1.5
권역별         수도권           1.9     1.4     1.3
            충청권           3.8     2.5     2.8
            호남권           2.7     2.2     2.1
            동북권           2.0     1.6     1.4
            동남권           2.4     1.3     1.5
인터넷 이용 시간별  1시간 미만        2.2     1.8     1.8
            1~2시간 미만      1.6     1.0     1.3
            2~3시간 미만      2.3     1.3     1.2
            3~5시간 미만      2.5     1.9     1.8
            5시간 이상        2.7     1.9     1.9
가정형편별       상위            3.7     3.2     2.8
            중위            2.1     1.3     1.3
            하위            4.5     4.7     4.6
학업성적별       상위권           2.8     1.9     2.0
            중위권           2.1     1.4     1.4
            하위권           3.2     2.7     2.7
사이버폭력 예방교육별 경험 있음         2.1     1.3     1.3
            경험 없음         4.1     4.3     3.8

In [4]:
# 함수 이름 : withdraw
# 함수 기능 : 해당 데이터프레임에서 연령별, 학력별, 소득별 자료를 반환하는 함수.
# ======================================================================================
def withdraw_student(cyberDF) :
    #cyberDF파일에서 학령별 자료 추출
    cyberDF_age=cyberDF.xs('학령별', level = 0)

    #cyberDF파일에서 가정형편별 자료 추출
    cyberDF_edu=cyberDF.xs('가정형편별', level = 0)

    #cyberDF파일에서 학업성적별 자료 추출
    cyberDF_income=cyberDF.xs('학업성적별', level = 0)

    return cyberDF_age.T, cyberDF_edu.T, cyberDF_income.T

In [5]:
# 사이버폭력_가해_경험_학령별, 가정형편별, 학업성적별 자료 불러오기
file1 = '../학생_가해경험/사이버폭력_가해_경험_20240119191526.csv'

# 결과값으로 info() 출력
cyberDF1 = clean(file1)

# 사이버폭력_가해_경험_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF1_age, cyberDF1_edu, cyberDF1_income = withdraw_student(cyberDF1)
cyberDF1_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   가해 경험률    30 non-null     float64
 1   사이버 언어폭력  30 non-null     float64
 2   사이버 명예훼손  30 non-null     float64
 3   사이버 스토킹   30 non-null     float64
 4   사이버 성폭력   30 non-null     float64
 5   신상정보 유출   30 non-null     float64
 6   사이버 따돌림   30 non-null     float64
 7   사이버 갈취    30 non-null     float64
 8   사이버 강요    30 non-null     float64
dtypes: float64(9)
memory usage: 4.0 KB

특성별(2)    초등학교   중학교  고등학교
가해 경험률    22.1  24.8  14.5
사이버 언어폭력  19.9  23.6  13.9
사이버 명예훼손   5.7   6.9   3.3
사이버 스토킹    1.9   2.8   1.5
사이버 성폭력    1.5   2.3   1.5
신상정보 유출    1.8   3.8   1.8
사이버 따돌림    2.7   2.6   1.7
사이버 갈취     1.1   2.3   1.4
사이버 강요     1.6   1.9   1.2

In [6]:
# 사이버폭력_가해_경로_학령별, 가정형편별, 학업성적별 자료 불러오기
file2 = '../학생_가해경험/사이버폭력_가해_경험_경로_20240119192228.csv'
cyberDF2 = clean(file2)

# 사이버폭력_가해_경로_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF2_age, cyberDF2_edu, cyberDF2_income = withdraw_student(cyberDF2)
cyberDF2_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 7 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   문자 및 인스턴트 메시지 (카카오톡 라인 페이스북 메신저 텔레그램 등)  30 non-null     float64
 1   SNS (페이스북 인스타그램 블로그 등)                   30 non-null     float64
 2   온라인 게임                                   30 non-null     float64
 3   커뮤니티·동호회 (네이버·다음카페 블라인드 에스크 등)           30 non-null     float64
 4   개인 방송 서비스(유튜브 아프리카TV 트위치 틱톡 등)           30 non-null     float64
 5   메타버스(제페토 이프렌드 등)                         30 non-null     float64
 6   기타                                       30 non-null     float64
dtypes: float64(7)
memory usage: 3.6 KB

특성별(2)                                   초등학교   중학교  고등학교
문자 및 인스턴트 메시지 (카카오톡 라인 페이스북 메신저 텔레그램 등)  44.6  39.4  29.1
SNS (페이스북 인스타그램 블로그 등)                    8.6  21.7  19.3
온라인 게임                                   48.9  46.4  53.5
커뮤니티·동호회 (네이버·다음카페 블라인드 에스크 등)            1.5   3.7   3.3
개인 방송 서비스(유튜브 아프리카TV 트위치 틱톡 등)            3.9   3.5   6.2
메타버스(제페토 이프렌드 등)                          2.1   1.5   1.2
기타                                        2.8   0.8   0.1

In [7]:
# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 불러오기
file2 = '../학생_가해경험/사이버폭력_가해_경험_경로_20240119192228.csv'
cyberDF2 = clean(file2)

# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF2_age, cyberDF2_edu, cyberDF2_income = withdraw_student(cyberDF2)
cyberDF2_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 7 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   문자 및 인스턴트 메시지 (카카오톡 라인 페이스북 메신저 텔레그램 등)  30 non-null     float64
 1   SNS (페이스북 인스타그램 블로그 등)                   30 non-null     float64
 2   온라인 게임                                   30 non-null     float64
 3   커뮤니티·동호회 (네이버·다음카페 블라인드 에스크 등)           30 non-null     float64
 4   개인 방송 서비스(유튜브 아프리카TV 트위치 틱톡 등)           30 non-null     float64
 5   메타버스(제페토 이프렌드 등)                         30 non-null     float64
 6   기타                                       30 non-null     float64
dtypes: float64(7)
memory usage: 3.6 KB

특성별(2)                                   초등학교   중학교  고등학교
문자 및 인스턴트 메시지 (카카오톡 라인 페이스북 메신저 텔레그램 등)  44.6  39.4  29.1
SNS (페이스북 인스타그램 블로그 등)                    8.6  21.7  19.3
온라인 게임                                   48.9  46.4  53.5
커뮤니티·동호회 (네이버·다음카페 블라인드 에스크 등)            1.5   3.7   3.3
개인 방송 서비스(유튜브 아프리카TV 트위치 틱톡 등)            3.9   3.5   6.2
메타버스(제페토 이프렌드 등)                          2.1   1.5   1.2
기타                                        2.8   0.8   0.1

In [8]:
# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 불러오기
file3 = '../학생_가해경험/사이버폭력_가해_대상_20240119191755.csv'
cyberDF3 = clean(file3)

# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF3_age, cyberDF3_edu, cyberDF3_income = withdraw_student(cyberDF3)
cyberDF3_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   친한 친구          30 non-null     float64
 1   전혀 모르는 사람      30 non-null     float64
 2   얼굴만 아는 사이      30 non-null     float64
 3   선후배            30 non-null     float64
 4   온라인에서 알게 된 사람  30 non-null     float64
 5   유명인            30 non-null     float64
dtypes: float64(6)
memory usage: 3.3 KB

특성별(2)         초등학교   중학교  고등학교
친한 친구          41.4  39.0  25.2
전혀 모르는 사람      36.3  35.6  47.6
얼굴만 아는 사이       5.2   5.9   8.0
선후배             3.5   2.7   0.3
온라인에서 알게 된 사람  12.7  13.7  15.1
유명인             0.9   3.1   3.7

In [9]:
# 사이버폭력_가해자_유형_학령별, 가정형편별, 학업성적별 자료 불러오기
file4 = '../학생_가해경험/사이버폭력_가해자_유형_20240122011023.csv'
cyberDF4 = clean(file4)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   전혀 모르는 사람      30 non-null     float64
 1   친한 친구          30 non-null     float64
 2   얼굴만 아는 사이      30 non-null     float64
 3   선후배            30 non-null     float64
 4   온라인에서 알게 된 사람  30 non-null     float64
dtypes: float64(5)
memory usage: 3.1 KB

In [10]:
# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF4_age, cyberDF4_edu, cyberDF4_income = withdraw_student(cyberDF4)
cyberDF4_age

특성별(2)         초등학교   중학교  고등학교
전혀 모르는 사람      39.5  42.4  50.0
친한 친구          35.1  30.5  24.8
얼굴만 아는 사이       7.3  10.1  10.4
선후배             4.9   3.6   1.6
온라인에서 알게 된 사람  13.2  13.4  13.1

In [11]:
# 사이버폭력_가해_심리상태_학령별, 가정형편별, 학업성적별 자료 불러오기 _ 정당한 행동이라고 생각한 유형.
file5 = '../학생_가해경험/사이버폭력_가해_경험_후_심리상태__정당한_행동이라고_생각했음_20240119192603.csv'
cyberDF5 = clean(file5)

# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF5_age, cyberDF5_edu, cyberDF5_income = withdraw_student(cyberDF5)
cyberDF5_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  30 non-null     float64
 1   그렇지 않다     30 non-null     float64
 2   그렇다        30 non-null     float64
 3   매우 그렇다     30 non-null     float64
dtypes: float64(4)
memory usage: 2.9 KB

특성별(2)     초등학교   중학교  고등학교
전혀 그렇지 않다  56.5  34.8  28.5
그렇지 않다     24.8  32.0  25.2
그렇다        13.1  24.7  34.1
매우 그렇다      5.6   8.5  12.2

In [12]:
# 사이버폭력_가해_심리상태_학령별, 가정형편별, 학업성적별 자료 불러오기 _ 아무느낌이 없음.
file6 = '../학생_가해경험/사이버폭력_가해_경험_후_심리상태__아무런_느낌이_없었음_20240119192643.csv'
cyberDF6 = clean(file6)

# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF6_age, cyberDF6_edu, cyberDF6_income = withdraw_student(cyberDF6)
cyberDF6_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  30 non-null     float64
 1   그렇지 않다     30 non-null     float64
 2   그렇다        30 non-null     float64
 3   매우 그렇다     30 non-null     float64
dtypes: float64(4)
memory usage: 2.9 KB

특성별(2)     초등학교   중학교  고등학교
전혀 그렇지 않다  52.3  32.5  29.9
그렇지 않다     25.4  30.4  29.0
그렇다        14.9  24.9  26.4
매우 그렇다      7.4  12.2  14.6

In [13]:
# 사이버폭력_가해_심리상태_학령별, 가정형편별, 학업성적별 자료 불러오기 _ _문제가_생길_것_같아_걱정되었음
file7 = '../학생_가해경험/사이버폭력_가해_경험_후_심리상태__문제가_생길_것_같아_걱정되었음_20240119192624.csv'
cyberDF7 = clean(file7)

# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF7_age, cyberDF7_edu, cyberDF7_income = withdraw_student(cyberDF7)
cyberDF7_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  30 non-null     float64
 1   그렇지 않다     30 non-null     float64
 2   그렇다        30 non-null     float64
 3   매우 그렇다     30 non-null     float64
dtypes: float64(4)
memory usage: 2.9 KB

특성별(2)     초등학교   중학교  고등학교
전혀 그렇지 않다  18.4  25.7  34.7
그렇지 않다     14.6  29.0  28.5
그렇다        37.5  28.7  26.0
매우 그렇다     29.6  16.6  10.8

In [14]:
# 사이버폭력_가해_심리상태_학령별, 가정형편별, 학업성적별 자료 불러오기 _ 흥미롭고 재미있었음.
file8 = '../학생_가해경험/사이버폭력_가해_경험_후_심리상태__흥미롭고_재미있었음_20240119192633.csv'
cyberDF8 = clean(file8)

# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF8_age, cyberDF8_edu, cyberDF8_income = withdraw_student(cyberDF8)
cyberDF8_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  30 non-null     float64
 1   그렇지 않다     30 non-null     float64
 2   그렇다        30 non-null     float64
 3   매우 그렇다     30 non-null     float64
dtypes: float64(4)
memory usage: 2.9 KB

특성별(2)     초등학교   중학교  고등학교
전혀 그렇지 않다  77.7  54.4  50.5
그렇지 않다     15.9  31.0  27.8
그렇다         5.1  11.5  15.6
매우 그렇다      1.3   3.2   6.1

In [15]:
# 사이버폭력_가해_심리상태_학령별, 가정형편별, 학업성적별 자료 불러오기  (5) 상대방에게 미안하고 후회스러움.
file9 = '../학생_가해경험/사이버폭력_가해_경험_후_심리상태__상대방에게_미안하고_후회스러웠음_20240119192614.csv'
cyberDF9 = clean(file9)

# 사이버폭력_가해_대상_학령별, 가정형편별, 학업성적별 자료 추출
cyberDF9_age, cyberDF9_edu, cyberDF9_income = withdraw_student(cyberDF9)
cyberDF9_age

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30 entries, ('전체', '소계') to ('사이버폭력 예방교육별', '경험 없음')
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   전혀 그렇지 않다  30 non-null     float64
 1   그렇지 않다     30 non-null     float64
 2   그렇다        30 non-null     float64
 3   매우 그렇다     30 non-null     float64
dtypes: float64(4)
memory usage: 2.9 KB

특성별(2)     초등학교   중학교  고등학교
전혀 그렇지 않다  14.9  22.4  28.7
그렇지 않다     11.6  19.5  24.5
그렇다        39.1  36.3  33.4
매우 그렇다     34.4  21.8  13.3